FlightSystemManagement/Areas/Admin/Controllers/PlaneAdminController.cs
using FlightSystemManagementAPI.Models.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Numerics;
using System.Text;

namespace FlightSystemManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PlaneAdminController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly HttpClient _httpclient;


        public PlaneAdminController(IHttpClientFactory httpClientFactory,HttpClient httpClient)
        {
            _httpclient = httpClient;
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            var httpClient = _httpClientFactory.CreateClient();
            var response = await httpClient.GetAsync("https://localhost:7298/api/Plane");

            // Kiểm tra phản hồi từ Web API
            if (response.IsSuccessStatusCode)
            {
                // Đọc nội dung phản hồi
                var responseData = await response.Content.ReadAsStringAsync();
                var planes = JsonConvert.DeserializeObject<List<PlaneInfo>>(responseData);
                return View(planes);

            }
            else
            {
                return StatusCode((int)response.StatusCode);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var httpClient = _httpClientFactory.CreateClient();
            var response = await httpClient.GetAsync("https://localhost:7298/api/Plane");

            // Kiểm tra phản hồi từ Web API
            if (response.IsSuccessStatusCode)
            {
                // Đọc nội dung phản hồi
                var responseData = await response.Content.ReadAsStringAsync();
                var plane = JsonConvert.DeserializeObject<List<PlaneInfo>>(responseData);
                return View();
            }
            else
            {
                return StatusCode((int)response.StatusCode);
            }
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(PlaneInfo planemodel)
        {
            // Gửi yêu cầu POST đến API
            var response = await _httpclient.GetAsync("https://localhost:7298/api/Plane");
            var responseData = await response.Content.ReadAsStringAsync();
            var planes = JsonConvert.DeserializeObject<List<PlaneInfo>>(responseData);

            PlaneInfo plane = new PlaneInfo
            {
                APlaneName = planemodel.APlaneName,
                APlaneCapity = planemodel.APlaneCapity,
                Price = planemodel.Price,
            };
            var jsonPLane = JsonConvert.SerializeObject(plane);

            // Tạo nội dung yêu cầu HTTP
            var content = new StringContent(jsonPLane, Encoding.UTF8, "application/json");
            var responsepost = await _httpclient.PostAsync("https://localhost:7298/api/Plane/create", content);

            // Xử lý phản hồi từ API
            if (responsepost.IsSuccessStatusCode)
            {
                // Phản hồi thành công
                return RedirectToAction("Index");
            }
            else
            {
                // Xử lý lỗi
                var errorResponse = await responsepost.Content.ReadAsStringAsync();
                ModelState.AddModelError("", errorResponse);
                return View(plane);
            }
        }
        
        public async Task<IActionResult> Delete(int Id)
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7298/api/Plane");
                var response = await client.DeleteAsync($"PLane/{Id}");
                
                if (response.IsSuccessStatusCode)
                    return RedirectToAction("Index"); // Chuyển hướng đến trang danh sách sản phẩm
                else
                {
                    var errorMessage = await response.Content.ReadAsStringAsync();
                    ModelState.AddModelError("", errorMessage);
                }
                return RedirectToAction("Index");
            }

        }
    }
}

FlightSystemManagement/Areas/Admin/Views/PlaneAdmin/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@model PlaneInfo
<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    th {
        background-color: #f2f2f2;
    }
</style>
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span> Dashboard
    </h3>
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
            </li>
        </ul>
    </nav>
</div>


<form asp-action="Create" enctype="multipart/form-data" method="post">    
    <div class="form-group">
        <label>Tên máy bay</label>
        <input asp-for="APlaneName" class="form-control" />
        <span asp-validation-for="APlaneName" class="text-danger" />
    </div>

    <div class="form-group">
        <label>Số lượng hành khách</label>
        <input asp-for="APlaneCapity" class="form-control" />
        <span asp-validation-for="APlaneCapity" class="text-danger" />
    </div>

    <div class="form-group">
        <label>Giá cả</label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger" />
    </div>
    <div class="form-group">
        <button class="btn btn-primary">Thêm</button>
    </div>
</form>
<a asp-action="Index" asp-controller="PlaneAdmin">Quay trở lại</a>

FlightSystemManagement/Areas/Admin/Views/PlaneAdmin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@model List<PlaneInfo>

<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    th {
        background-color: #f2f2f2;
    }
</style>
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span> Dashboard
    </h3>
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
            </li>
        </ul>
    </nav>
</div>
<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Plane Name</th>
            <th>Plane Capity</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th>@item.PlaneID</th>
                <td>@item.APlaneName</td>
                <td>@item.APlaneCapity</td>
                <td>@item.Price.ToString("#,#00")</td>
                <td>
                    <a asp-action="Create" asp-controller="PlaneAdmin"><i class="fa-solid fa-circle-plus"></i></a>
                    @* <a asp-action="Edit" class="btn btn-warning" asp-controller="PlaneAdmin"
                asp-route-id=@item.PlaneID><i class="mdi-border-color"></i></a> *@
                    <a asp-action="Delete" asp-route-id="@item.PlaneID" type="submit"><i class="fa-regular fa-trash-can"></i></a>
                </td>
            </tr>
        }

    </tbody>
    <!-- Add more rows as needed -->
</table>